### ISSUE TITLE
UI 크기 조절??

### ISSUE THREAD

**Issue by jongfeel** [minjoonee/ARculture#2]
UI 구성으로 Vector3값으로 조정하라고 하셨는데  화면에 카메라 인식 범위를 조정해주는 것도 나쁘진 않은 것 같다. 그래서 그렇게 변경 완료

**Comment by jongfeel** [comment]
Project > Card에는 간단하게만 적고
이렇게 issue와 연결 시켜서 디테일한 걸 적으면 좋습니다.

여기에는 이미지 파일 첨부도 가능하고 소스코드 링크도 할 수 있어요.

**Comment by Minjoon2** [comment]
오...알겠습니다!
