### ISSUE TITLE
한이음 교통비 신청

### ISSUE THREAD

**Issue by jongfeel** [minjoonee/ARculture#6]
![image](https://user-images.githubusercontent.com/17442457/58062015-a0e16800-7bb3-11e9-9173-407d977da9a1.png)

제가 멘토링활동보고서에 미팅 내용과 사진을 올렸으니 참고하셔서 작성하시고
교통비 신청 꼭 하세요.
개별 작성해야 하고 한이음측 메일 hanium@naver.com로 월말까지 제출해야 한다고 하네요.

**Comment by Song-gicheon** [comment]
넵

**Comment by Minjoon2** [comment]
네
